name: land
description: Tool for generating localization files in Dart
version: 0.0.2
homepage: https://github.com/lslv1243/land

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  path: ^1.8.0
  intl: ^0.17.0
  dart_style: ^2.2.2
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
