name: land
description: >
  LAND is a robust Dart package offering efficient generation of localization files for Dart and Flutter applications. It supports complex ICU messages, seamlessly integrates with project workflows, and offers global installation for multi-project usage.
version: 0.0.6
homepage: https://github.com/lslv1243/land

environment:
  sdk: '>=2.16.1 <3.0.0'

executables:
  land: land

dependencies:
  args: ^2.3.0
  path: ^1.8.0
  intl: ^0.17.0
  dart_style: ^2.2.2
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
